name: Repository Maintenance

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  stale:
    name: Mark stale issues and PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale due to inactivity. It will be closed if no further activity occurs.'
          stale-pr-message: 'This pull request has been automatically marked as stale due to inactivity. It will be closed if no further activity occurs.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          days-before-stale: 60
          days-before-close: 7
          exempt-issue-labels: 'pinned,security,enhancement,bug'
          exempt-pr-labels: 'pinned,security,work-in-progress'

  greeting:
    name: Greet first-time contributors
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' || github.event_name == 'pull_request'
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thank you for opening your first issue in the PXON project! Someone will review it soon.'
          pr-message: 'Thanks for submitting your first pull request to PXON! We appreciate your contribution and will review it shortly.'

  labeler:
    name: Auto-label PRs
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
